"""empty message

Revision ID: 51443829da2e
Revises: aab36aeda88e
Create Date: 2019-03-27 21:28:57.460010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51443829da2e'
down_revision = 'aab36aeda88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
