version: '3'

services:
  server:
    container_name: flask_project
    build: .
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/flask_project
    depends_on:
      - database

  database:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

